"""Opponent fitted to Yuki0x80's observed play in episode 112813626.

Observed: peak herd 7, 368 hires, 3 quadrants, crop mix {'MELON': 338, 'STRAWBERRY': 190, 'WHEAT': 184},
sold {'FERTILIZER': 164, 'MELON': 154, 'WHEAT': 147, 'MILK': 141}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_yuki0x80', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 7.0, 'barn_r': 3.0, 'workers_hi': 10.0, 'max_land': 3.0, 'v_fert': 2.0, 'sheep_share': 0.2, 'plant_radius': 7.0})
agent = _base.agent
