"""Opponent fitted to Ronel Abraham Mathew's observed play in episode 113192360.

Observed: peak herd 15, 224 hires, 2 quadrants, crop mix {'STRAWBERRY': 485, 'MELON': 122},
sold {'STRAWBERRY': 222, 'FERTILIZER': 167, 'MILK': 159, 'WOOL': 152}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_ronel_abraham_math', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 15.0, 'barn_r': 4.0, 'workers_hi': 7.466666666666667, 'max_land': 2.0, 'v_fert': 3.0, 'sheep_share': 0.2, 'plant_radius': 9.0})
agent = _base.agent
