"""Opponent fitted to NiuLAI's observed play in episode 112886923.

Observed: peak herd 17, 283 hires, 3 quadrants, crop mix {'STRAWBERRY': 411, 'WHEAT': 359, 'MELON': 115},
sold {'WHEAT': 318, 'FERTILIZER': 200, 'MILK': 190, 'STRAWBERRY': 162}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_niulai', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 17.0, 'barn_r': 4.0, 'workers_hi': 9.433333333333334, 'max_land': 3.0, 'v_fert': 3.0, 'sheep_share': 0.2, 'plant_radius': 7.0})
agent = _base.agent
