"""Opponent fitted to Rohin Kethipally's observed play in episode 112872908.

Observed: peak herd 19, 253 hires, 1 quadrants, crop mix {'MELON': 183, 'STRAWBERRY': 63, 'CARROT': 14},
sold {'MILK': 298, 'FERTILIZER': 285, 'MELON': 108, 'WHEAT': 66}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_rohin_kethipally', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 19.0, 'barn_r': 4.0, 'workers_hi': 8.433333333333334, 'max_land': 1.0, 'v_fert': 3.0, 'sheep_share': 0.2, 'plant_radius': 7.0})
agent = _base.agent
