"""Opponent fitted to nono00's observed play in episode 113195895.

Observed: peak herd 13, 256 hires, 3 quadrants, crop mix {'STRAWBERRY': 383, 'WHEAT': 350, 'MELON': 169},
sold {'WHEAT': 225, 'FERTILIZER': 201, 'STRAWBERRY': 192, 'WOOL': 180}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_nono00', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 13.0, 'barn_r': 4.0, 'workers_hi': 8.533333333333333, 'max_land': 3.0, 'v_fert': 3.0, 'sheep_share': 0.45, 'plant_radius': 7.0})
agent = _base.agent
