"""Opponent fitted to igeo kK's observed play in episode 112947496.

Observed: peak herd 11, 178 hires, 2 quadrants, crop mix {'MELON': 275, 'WHEAT': 106, 'STRAWBERRY': 96},
sold {'FERTILIZER': 228, 'MELON': 156, 'EGG': 154, 'MILK': 114}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_igeo_kk', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 11.0, 'barn_r': 4.0, 'workers_hi': 5.933333333333334, 'max_land': 2.0, 'v_fert': 3.0, 'sheep_share': 0.2, 'plant_radius': 7.0})
agent = _base.agent
