"""Opponent fitted to sansm1's observed play in episode 113193497.

Observed: peak herd 14, 287 hires, 3 quadrants, crop mix {'STRAWBERRY': 632, 'MELON': 204, 'WHEAT': 158},
sold {'WHEAT': 1131, 'MILK': 594, 'STRAWBERRY': 448, 'FERTILIZER': 352}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_sansm1', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({'herd': 14.0, 'barn_r': 4.0, 'workers_hi': 9.566666666666666, 'max_land': 3.0, 'v_fert': 3.0, 'sheep_share': 0.2, 'plant_radius': 9.0})
agent = _base.agent
