"""Fit a TUNE profile to each real opponent seen in a downloaded replay.

Every local opponent so far descends from this agent, which is why local
measurement kept disagreeing with the ladder: the whole pool shared this
agent's blind spots (none of them collected fertilizer either). Their code is
not available, but their *behaviour* is, and the agent is flexible enough to
imitate the parts that matter -- herd size, crop mix, hiring, land, how hard
they push livestock. That gives a pool that at least misses in the same places
the real field does.

    python tools/fit_opponent.py ~/Downloads/*.json --out opponents/
"""
import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TEMPLATE = '''"""Opponent fitted to {name}'s observed play in episode {eid}.

Observed: peak herd {herd}, {hires} hires, {land} quadrants, crop mix {mix},
sold {sold}. Generated by tools/fit_opponent.py -- behaviour only, not code.
"""
import importlib.util
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    '_base_{slug}', Path(__file__).resolve().parents[1] / 'agent' / 'main.py')
_base = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_base)
_base.TUNE.update({tune})
agent = _base.agent
'''


def profile(path):
    d = json.load(open(path))
    st = d['steps']
    teams = d['info'].get('TeamNames', ['?', '?'])
    me = 0 if 'Amritesh' in str(teams[0]) else 1
    opp = 1 - me
    peak_herd = 0
    crops = Counter()
    sold = Counter()
    hires = 0
    land = 1
    fert = 0
    for i, s in enumerate(st):
        farm = s[0]['observation']['farms'][opp]
        n = 0
        for row in farm['tiles']:
            for t in row:
                if isinstance(t, dict):
                    if 'animal' in t:
                        n += 1
                    elif t.get('kind') == 'PLANT' and i % 24 == 12:
                        crops[t['crop']] += 1
        peak_herd = max(peak_herd, n)
        land = max(land, len(farm.get('unlocked_quadrants', ['NW'])))
        a = s[opp].get('action') or {}
        for u in [a.get('farmer')] + list(a.get('hands', [])):
            if u and u[0] == 'COLLECT_FERTILIZER':
                fert += 1
        for o in a.get('market', []):
            if o[0] == 'HIRE':
                hires += 1
            elif o[0] == 'SELL':
                sold[o[1]] += o[2]
    total = sum(crops.values()) or 1
    straw = crops.get('STRAWBERRY', 0) / total
    return {
        'name': str(teams[opp]), 'eid': d['info'].get('EpisodeId', '?'),
        'herd': peak_herd, 'hires': hires, 'land': land,
        'mix': dict(crops.most_common(3)), 'sold': dict(sold.most_common(4)),
        'fert': fert,
        'tune': {
            'herd': float(max(4, peak_herd)),
            'barn_r': 4.0 if peak_herd > 10 else 3.0,
            'workers_hi': max(4.0, min(10.0, hires / 30.0)),
            'max_land': float(land),
            # A player who collects a lot of fertilizer is pushing livestock;
            # one who does not is a crop player.
            'v_fert': 3.0 if fert > 200 else (2.0 if fert > 50 else 0.0),
            'sheep_share': 0.45 if sold.get('WOOL', 0) > sold.get('MILK', 0) else 0.2,
            'plant_radius': 9.0 if straw > 0.5 else 7.0,
        },
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('files', nargs='+')
    ap.add_argument('--out', default='opponents')
    args = ap.parse_args()
    for f in args.files:
        p = profile(f)
        slug = ''.join(ch.lower() if ch.isalnum() else '_' for ch in p['name'])[:18]
        dest = ROOT / args.out / f'real_{slug}.py'
        fields = {k: v for k, v in p.items() if k != 'tune'}
        dest.write_text(TEMPLATE.format(slug=slug, tune=repr(p['tune']), **fields))
        print(f"{p['name']:24s} herd {p['herd']:2d} hires {p['hires']:3d} "
              f"land {p['land']} fert {p['fert']:3d} -> {dest.name}")


if __name__ == '__main__':
    main()
